---
server:
    install: '1'
    packages: [vim, htop, iotop, bwm-ng, git]
    timezone: UTC
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: design-patterns, ip: 192.168.11.2, sharedfolder: ./, enableWindows: '1', useVagrantCloud: '1', syncType: nfs }
php:
    install: '1'
    ppa: php
    packages:
      - php7.0-cli
      - php7.0-intl
      - php7.0-mcrypt
      - php7.0-mysql
      - php7.0-curl
      - php7.0-json
      - php7.0-xml
      - php7.0-mbstring

xdebug:
    install: '1'

composer:
    timeout: 2400